name: Backend CI/CD
run-name:  ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
on: [push]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
          persist-credentials: false
      - name: List files in the repository
        run: |
          ls -Ahl ${{ github.workspace }}
