name: Backend CI/CD
run-name:  ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
on: [push]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          # cache: 'pipenv'
      - name: Test main.py
        run: python main.py
